Update longhorn-engine-launcher
to: af86bfd22d764aba82f4c7c3aee08a2b9ce228dc

1. Add `launcher-id` to identify engine instance
2. Require ID when start/shutdown frontend
3. Remove rpc code for launcher. Use launcher as client instead.
4. Shutdown frontend to launcher needs to be called every time controller
decided to shutdown the frontend, otherwise it will cause cache inconsistent if
controller was reused. The issue was reproduced on drone:

```
=================================== FAILURES ===================================
________________________ test_backup_with_backing_file _________________________

backing_dev = <frontend.blockdev instance at 0x7f5445aecd40>

    def test_backup_with_backing_file(backing_dev):  # NOQA
        dev = backing_dev  # NOQA

        offset = 0
        length = 256

        snap0 = cmd.snapshot_create()
        before = read_dev(dev, offset, length)
        assert before != ""
        snap0_checksum = common.checksum_dev(dev)

        exists = read_from_backing_file(offset, length)
>       assert before == exists
E       assert 'uitjupbkdcpk...0\x00\x00\x00' == 'xEoyC6jSBAqgp...TlX7HBCg3hHlW'
```